version: "3"

services:
  app:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: ./.devcontainer/dockerfile
      args:
        node_version: 20
        python_version: 3.11
        terraform_version: 1.9.0
    volumes:
      - ..:/workspace:cached
    command: sleep infinity